# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  itask:
    image: itask
    container_name: itask
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5191:80"
