# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  itask:
    image: itask
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5191:80"
    volumes: 
      - /var
    depends_on:
      - mssqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Wr7u4e8b
    expose:
      - "5432"
    restart: always

volumes:
  db-data: 

