# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  itask:
    image: itask
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5191:80"
    volumes: 
      - /var
    depends_on:
      - mssqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Passw0rd
    ports: 
      - 1401:1433
    expose:
      - "5191"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

